name: Update dependencies

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update dev dependencies and deploy
        uses: actions/checkout@v2
        env:
          NPM_TOKEN: ${{ secrets.BUILD_NPM_TOKEN }}
      - run: |
          npm update --save-dev
          npm run build
          npm run predeploy
          npm run deploy
          npm run build-api
